Repository povio/PovioKit, pull requests merged in 2022-09, with the labels that each got.

#185 UI/GradientView - additional initializer
  Sources/UI/GradientView/GradientView.swift
Labels: rebase squash merge

#187 Chore/Measurements
  README.md
  Sources/Core/Extensions/Foundation/Double+Povio.swift
  Tests/Tests/Core/Extensions/Foundation/DoubleTests.swift
Labels: needs review

#188 Chore/Public access in ASB
  Sources/Core/Utilities/AttributedStringBuilder/AttributedStringBuilder.swift
Labels: rebase squash merge

#189 Chore/async delay tests
  Tests/Tests/PromiseKit/PromiseTests.swift
Labels: needs review, proposal

#190 Chore/Final implementations
  Sources/Core/Utilities/AppVersionValidator/AppVersionValidator.swift
  Sources/Core/Utilities/Broadcast/Broadcast.swift
  Sources/Core/Utilities/BundleReader/BundleReader.swift
  Sources/Core/Utilities/DispatchTimer/DispatchTimer.swift
  Sources/Core/Utilities/Logger/Logger.swift
  Sources/Core/Utilities/SignInWithApple/SignInWithApple+Models.swift
  Sources/Core/Utilities/SignInWithApple/SignInWithApple.swift
  Sources/Networking/AlamofireNetworkClient/AlamofireNetworkClient.swift
  Sources/Networking/AlamofireNetworkClient/AlamofireRetryInterceptor.swift
Labels: needs review

#192 Chore/Deprecate DataSource protocol
  README.md
  Resources/Core/Protocols/DataSource/README.md
  Sources/Core/Protocols/DataSource/DataSourceType.swift
  Sources/Core/Protocols/DataSource/RowType.swift
  Sources/Core/Protocols/DataSource/SectionType.swift
Labels: needs review

#195 Chore/Remove deprecated code
  MIGRATING.md
  Sources/Core/Extensions/UIKit/UICollectionView+Povio.swift
  Sources/Core/Extensions/UIKit/UIImage+Povio.swift
  Sources/Core/Extensions/UIKit/UITableView+Povio.swift
  Sources/Core/Utilities/SignInWithApple/SignInWithApple+Models.swift
  Sources/Core/Utilities/SignInWithApple/SignInWithApple.swift
  Sources/Networking/AlamofireNetworkClient/AlamofireNetworkClient.swift
  Sources/Networking/AlamofireNetworkClient/AlamofireRetryInterceptor.swift
  Sources/UI/ActionButton/ActionButton.swift
Labels: needs review

#196 Chore/Release updates
  MIGRATING.md
  Package.swift
  README.md
  Resources/Core/Utilities/AttributedStringBuilder/README.md
  Sources/Core/Extensions/Foundation/URL+Povio.swift
Labels: rebase squash merge

#197 Fix/Release issues
  Sources/Networking/AlamofireNetworkClient/AlamofireNetworkClient.swift
Labels: rebase squash merge

#194 Release/2.0.0
  .github/workflows/CI.yml
  .github/workflows/Tests.yml
  .swiftpm/xcode/xcshareddata/xcschemes/PovioKit-Package.xcscheme
  MIGRATING.md
  Package.resolved
  Package.swift
  README.md
  Resources/Core/Protocols/DataSource/README.md
  Resources/Core/Utilities/AttributedStringBuilder/README.md
  Resources/Networking/AlamofireNetworkClient/README.md
  Sources/Core/Extensions/Foundation/Double+Povio.swift
  Sources/Core/Extensions/Foundation/URL+Povio.swift
  Sources/Core/Extensions/Other/SKStoreReviewController+PovioKit.swift
  Sources/Core/Extensions/UIKit/UICollectionView+Povio.swift
  Sources/Core/Extensions/UIKit/UIImage+Povio.swift
  Sources/Core/Extensions/UIKit/UITableView+Povio.swift
  Sources/Core/Protocols/DataSource/DataSourceType.swift
  Sources/Core/Protocols/DataSource/RowType.swift
  Sources/Core/Protocols/DataSource/SectionType.swift
  Sources/Core/Utilities/AppVersionValidator/AppVersionValidator.swift
  Sources/Core/Utilities/AttributedStringBuilder/AttributedStringBuilder.swift
  Sources/Core/Utilities/Broadcast/Broadcast.swift
  Sources/Core/Utilities/BundleReader/BundleReader.swift
  Sources/Core/Utilities/DispatchTimer/DispatchTimer.swift
  Sources/Core/Utilities/Logger/Logger.swift
  Sources/Core/Utilities/SignInWithApple/SignInWithApple+Models.swift
  Sources/Core/Utilities/SignInWithApple/SignInWithApple.swift
  Sources/Networking/AlamofireNetworkClient/AlamofireNetworkClient.swift
  Sources/Networking/AlamofireNetworkClient/AlamofireRetryInterceptor.swift
  Sources/Networking/AlamofireNetworkClient/OAuth/OAuthContainer.swift
  Sources/Networking/AlamofireNetworkClient/OAuth/OAuthCredentials.swift
  Sources/Networking/AlamofireNetworkClient/OAuth/OAuthInterceptor.swift
  Sources/PromiseKit/ConcurrentDispatch.swift
  Sources/PromiseKit/Future.swift
  Sources/PromiseKit/Promise.swift
  Sources/PromiseKit/Sequence.swift
  Sources/UI/ActionButton/ActionButton.swift
  Sources/UI/GradientView/GradientView.swift
  Tests/Tests/Core/Extensions/Foundation/DoubleTests.swift
  Tests/Tests/Core/Utilities/Throttler/ThrottlerTests.swift
  Tests/Tests/PromiseKit/PromiseTests.swift
Labels: rebase squash merge

#139 Feature/Textfield
  Package.swift
  README.md
  Resources/UI/TextField/README.md
  Sources/Core/Extensions/Foundation/Optional+Povio.swift
  Sources/UI/TextField/TextField.swift
Labels: rebase squash merge

#198 Feature/XCTAssert+URLRequest
  Sources/Core/Extensions/Other/XCTestCase+PovioKit.swift
  Tests/Tests/Core/Extensions/Other/XCTestCaseTests.swift
Labels: rebase squash merge

#207 Chore/Readme update
  README.md
Labels: needs review

#200 Chore/More unit tests
  Sources/Core/Utilities/DispatchTimer/DispatchTimer.swift
  Tests/Tests/Core/Extensions/UIKit/UITableViewCellTests.swift
  Tests/Tests/Core/Extensions/UIKit/UIViewTests.swift
  Tests/Tests/Core/Utilities/DispatchTimer/DispatchTimerTests.swift
Labels: rebase squash merge
